### ISSUE TITLE
关于顶点云的web服务配置

### ISSUE THREAD

**Issue by 1049451037** [Forec/zenith-cloud#1]
您好，我按照[这个文档](https://zenith-cloud.readthedocs.io/zh_CN/latest/web-installation.html#web-installation)配置，没有配置成功，比较不理解的地方就是安装的时候不需要配置数据库用户名密码之类的吗？

**Comment by Forec** [comment]
你好，具体错误信息是？这个仓库是上学时候做的一个课程作业，已经很久没维护。当时为了作业的迁移方便，用的 SQLite，不支持认证信息。如果需要的话，可以配置 MySQL 或者其他关系型数据库。

**Comment by 1049451037** [comment]
```shell
======================================================================
ERROR: test_rules (test_client_2.ZENITHClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 392, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/zenith-cloud/web/tests/test_client_2.py", line 11, in setUp
    db.drop_all()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 980, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 964, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 3875, in drop_all
    tables=tables)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1919, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1912, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2103, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
    e, dialect, self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 392, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

----------------------------------------------------------------------
Ran 14 tests in 0.057s

FAILED (errors=14)
Traceback (most recent call last):
  File "manage.py", line 151, in <module>
    manager.run()
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask/ctx.py", line 399, in __exit__
    self.auto_pop(exc_value)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask/ctx.py", line 387, in auto_pop
    self.pop(exc)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask/ctx.py", line 376, in pop
    app_ctx.pop(exc)
  File "/root/zenith-cloud/web/venv/lib/python3.5/site-packages/flask/ctx.py", line 193, in pop
    % (rv, self)
AssertionError: Popped wrong app context.  (<flask.ctx.AppContext object at 0x7f4da07427f0> instead of <flask.ctx.AppContext object at 0x7f4da0f82ba8>)
```

**Comment by 1049451037** [comment]
感觉是数据库连接有问题

**Comment by Forec** [comment]
1. 默认配置是 `windows`，修改 `manage.py` 里的 `app = create_app('windows')` 为 `app = create_app('linux')` 以启用 Linux 的配置文件
2. `cd /root/zenith-cloud/web && touch work.db && source venv/bin/activate && python3 manager.py simple_init`

**Comment by 1049451037** [comment]
still not working...same errors occurred.

**Comment by Forec** [comment]
先 `mkdir -p /root/zenith-cloud/web/temp` 再跑测试？

**Comment by 1049451037** [comment]
哇，确实可以了！Great!
